@NorthWindsEComm.Gateway_HostAddress = http://localhost:5075
@version = v1

GET {{NorthWindsEComm.Gateway_HostAddress}}/bff/{{version}}/fillCache
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response content-type is json", function () {
        const type = response.contentType.mimeType;
        client.assert(type === "application/json", `Expected 'application/json' but received '${type}'`);
    });
%}

###

GET {{NorthWindsEComm.Gateway_HostAddress}}/api/{{version}}/suppliers
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

GET {{NorthWindsEComm.Gateway_HostAddress}}/api/{{version}}/suppliers/1
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

GET {{NorthWindsEComm.Gateway_HostAddress}}/api/{{version}}/products
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

GET {{NorthWindsEComm.Gateway_HostAddress}}/api/{{version}}/products/1
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

GET {{NorthWindsEComm.Gateway_HostAddress}}/bff/{{version}}/products/79
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

GET {{NorthWindsEComm.Gateway_HostAddress}}/bff/{{version}}/categories/1
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

POST {{NorthWindsEComm.Gateway_HostAddress}}/administration/connect/token
Content-Type: application/x-www-form-urlencoded

client_id=admin&client_secret=secret&scope=admin&grant_type=client_credentials

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set("auth_token", response.body.access_token);
    });
%}

###

GET {{NorthWindsEComm.Gateway_HostAddress}}/administration/configuration
Content-Type: application/json
Authorization: Bearer {{auth_token}}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
        client.global.set("ocelot_config", response.body);
    });
%}

###

POST {{NorthWindsEComm.Gateway_HostAddress}}/administration/configuration
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{{ocelot_config}}

###

POST {{NorthWindsEComm.Gateway_HostAddress}}/api/{{version}}/products
Content-Type: application/json

{
  "productName": "Dog Treats",
  "supplierId": 8,
  "categoryId": 5,
  "quantityPerUnit": "24 treats",
  "unitPrice": 15.25,
  "unitsInStock": 12,
  "unitsOnOrder": 24,
  "reorderLevel": 15,
  "discontinued": false
}