@NorthWindsEComm.Products.Api_HostAddress = http://localhost:5158
@version = v1

GET {{NorthWindsEComm.Products.Api_HostAddress}}/{{version}}/products/
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

GET {{NorthWindsEComm.Products.Api_HostAddress}}/{{version}}/products/1
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###

GET {{NorthWindsEComm.Products.Api_HostAddress}}/{{version}}/products?categoryId=1
Accept: application/json

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

###
